#!/bin/sh

# update before run script
sudo apt update -y
sudo apt upgrade -y

# Keep it updated (automation)
sudo apt-get install unattended-upgrades
sudo dpkg-reconfigure --priority=medium unattended-upgrades

# failban
sudo apt install -y fail2ban
sudo systemctl enable fail2ban
sudo systemctl start fail2ban
# TODO: config failban


# net
sudo apt-get -y install htop net-tools tree curl wget vim git

# fish
sudo apt install -y fish
curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
fisher install jorgebucaran/nvm.fish

# nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
nvm install lts
nvm use lts

# java
sudo apt install openjdk-17-jdk

# Install nohang to prevent vps freeze
sudo add-apt-repository ppa:oibaf/test
sudo apt update
sudo apt install nohang
sudo systemctl enable -now nohang-desktop.service

# uidmap for no-root users
sudo apt-get install -y uidmap

# Install and configure Caddy
sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https curl
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
sudo apt update
sudo apt install caddy

# Install client mysql
 sudo apt install -y default-mysql-client

# update system
sudo apt update -y
sudo apt upgrade -y
