services:
  db:
    image: mysql:9.0.1-oraclelinux9
    restart: always
    ports:
      - "127.0.0.1:${MYSQL_PORT:-43060}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-example}"
    volumes:
      - ./db_data:/var/lib/mysql
